namespace MasterOnline.ErasoftContextMigrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class add_table_TEMP_BRG_MP_2nd : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.TEMP_BRG_MP",
                c => new
                    {
                        RecNum = c.Int(nullable: false, identity: true),
                        BRG_MP = c.String(maxLength: 50),
                        NAMA = c.String(maxLength: 30),
                        NAMA2 = c.String(maxLength: 30),
                        HJUAL = c.Double(nullable: false),
                        BERAT = c.Double(nullable: false),
                        PANJANG = c.Double(nullable: false),
                        LEBAR = c.Double(nullable: false),
                        TINGGI = c.Double(nullable: false),
                        Deskripsi = c.String(),
                        IDMARKET = c.Int(nullable: false),
                        HJUAL_MP = c.Double(nullable: false),
                        DISPLAY = c.Boolean(nullable: false),
                        DeliveryTempElevenia = c.String(maxLength: 10),
                        CATEGORY_CODE = c.String(maxLength: 50),
                        CATEGORY_NAME = c.String(maxLength: 250),
                        ACODE_1 = c.String(maxLength: 50),
                        ANAME_1 = c.String(maxLength: 250),
                        AVALUE_1 = c.String(maxLength: 250),
                        ACODE_2 = c.String(maxLength: 50),
                        ANAME_2 = c.String(maxLength: 250),
                        AVALUE_2 = c.String(maxLength: 250),
                        ACODE_3 = c.String(maxLength: 50),
                        ANAME_3 = c.String(maxLength: 250),
                        AVALUE_3 = c.String(maxLength: 250),
                        ACODE_4 = c.String(maxLength: 50),
                        ANAME_4 = c.String(maxLength: 250),
                        AVALUE_4 = c.String(maxLength: 250),
                        ACODE_5 = c.String(maxLength: 50),
                        ANAME_5 = c.String(maxLength: 250),
                        AVALUE_5 = c.String(maxLength: 250),
                        ACODE_6 = c.String(maxLength: 50),
                        ANAME_6 = c.String(maxLength: 250),
                        AVALUE_6 = c.String(maxLength: 250),
                        ACODE_7 = c.String(maxLength: 50),
                        ANAME_7 = c.String(maxLength: 250),
                        AVALUE_7 = c.String(maxLength: 250),
                        ACODE_8 = c.String(maxLength: 50),
                        ANAME_8 = c.String(maxLength: 250),
                        AVALUE_8 = c.String(maxLength: 250),
                        ACODE_9 = c.String(maxLength: 50),
                        ANAME_9 = c.String(maxLength: 250),
                        AVALUE_9 = c.String(maxLength: 250),
                        ACODE_10 = c.String(maxLength: 50),
                        ANAME_10 = c.String(maxLength: 250),
                        AVALUE_10 = c.String(maxLength: 250),
                        ACODE_11 = c.String(maxLength: 50),
                        ANAME_11 = c.String(maxLength: 250),
                        AVALUE_11 = c.String(maxLength: 250),
                        ACODE_12 = c.String(maxLength: 50),
                        ANAME_12 = c.String(maxLength: 250),
                        AVALUE_12 = c.String(maxLength: 250),
                        ACODE_13 = c.String(maxLength: 50),
                        ANAME_13 = c.String(maxLength: 250),
                        AVALUE_13 = c.String(maxLength: 250),
                        ACODE_14 = c.String(maxLength: 50),
                        ANAME_14 = c.String(maxLength: 250),
                        AVALUE_14 = c.String(maxLength: 250),
                        ACODE_15 = c.String(maxLength: 50),
                        ANAME_15 = c.String(maxLength: 250),
                        AVALUE_15 = c.String(maxLength: 250),
                        ACODE_16 = c.String(maxLength: 50),
                        ANAME_16 = c.String(maxLength: 250),
                        AVALUE_16 = c.String(maxLength: 250),
                        ACODE_17 = c.String(maxLength: 50),
                        ANAME_17 = c.String(maxLength: 250),
                        AVALUE_17 = c.String(maxLength: 250),
                        ACODE_18 = c.String(maxLength: 50),
                        ANAME_18 = c.String(maxLength: 250),
                        AVALUE_18 = c.String(maxLength: 250),
                        ACODE_19 = c.String(maxLength: 50),
                        ANAME_19 = c.String(maxLength: 250),
                        AVALUE_19 = c.String(maxLength: 250),
                        ACODE_20 = c.String(maxLength: 50),
                        ANAME_20 = c.String(maxLength: 250),
                        AVALUE_20 = c.String(maxLength: 250),
                        ACODE_21 = c.String(maxLength: 50),
                        ANAME_21 = c.String(maxLength: 250),
                        AVALUE_21 = c.String(maxLength: 250),
                        ACODE_22 = c.String(maxLength: 50),
                        ANAME_22 = c.String(maxLength: 250),
                        AVALUE_22 = c.String(maxLength: 250),
                        ACODE_23 = c.String(maxLength: 50),
                        ANAME_23 = c.String(maxLength: 250),
                        AVALUE_23 = c.String(maxLength: 250),
                        ACODE_24 = c.String(maxLength: 50),
                        ANAME_24 = c.String(maxLength: 250),
                        AVALUE_24 = c.String(maxLength: 250),
                        ACODE_25 = c.String(maxLength: 50),
                        ANAME_25 = c.String(maxLength: 250),
                        AVALUE_25 = c.String(maxLength: 250),
                        ACODE_26 = c.String(maxLength: 50),
                        ANAME_26 = c.String(maxLength: 250),
                        AVALUE_26 = c.String(maxLength: 250),
                        ACODE_27 = c.String(maxLength: 50),
                        ANAME_27 = c.String(maxLength: 250),
                        AVALUE_27 = c.String(maxLength: 250),
                        ACODE_28 = c.String(maxLength: 50),
                        ANAME_28 = c.String(maxLength: 250),
                        AVALUE_28 = c.String(maxLength: 250),
                        ACODE_29 = c.String(maxLength: 50),
                        ANAME_29 = c.String(maxLength: 250),
                        AVALUE_29 = c.String(maxLength: 250),
                        ACODE_30 = c.String(maxLength: 50),
                        ANAME_30 = c.String(maxLength: 250),
                        AVALUE_30 = c.String(maxLength: 250),
                        ACODE_31 = c.String(maxLength: 50),
                        ANAME_31 = c.String(maxLength: 250),
                        AVALUE_31 = c.String(maxLength: 250),
                        ACODE_32 = c.String(maxLength: 50),
                        ANAME_32 = c.String(maxLength: 250),
                        AVALUE_32 = c.String(maxLength: 250),
                        ACODE_33 = c.String(maxLength: 50),
                        ANAME_33 = c.String(maxLength: 250),
                        AVALUE_33 = c.String(maxLength: 250),
                        ACODE_34 = c.String(maxLength: 50),
                        ANAME_34 = c.String(maxLength: 250),
                        AVALUE_34 = c.String(maxLength: 250),
                        ACODE_35 = c.String(maxLength: 50),
                        ANAME_35 = c.String(maxLength: 250),
                        AVALUE_35 = c.String(maxLength: 250),
                        ACODE_36 = c.String(maxLength: 50),
                        ANAME_36 = c.String(maxLength: 250),
                        AVALUE_36 = c.String(maxLength: 250),
                        ACODE_37 = c.String(maxLength: 50),
                        ANAME_37 = c.String(maxLength: 250),
                        AVALUE_37 = c.String(maxLength: 250),
                        ACODE_38 = c.String(maxLength: 50),
                        ANAME_38 = c.String(maxLength: 250),
                        AVALUE_38 = c.String(maxLength: 250),
                        ACODE_39 = c.String(maxLength: 50),
                        ANAME_39 = c.String(maxLength: 250),
                        AVALUE_39 = c.String(maxLength: 250),
                        ACODE_40 = c.String(maxLength: 50),
                        ANAME_40 = c.String(maxLength: 250),
                        AVALUE_40 = c.String(maxLength: 250),
                        ACODE_41 = c.String(maxLength: 50),
                        ANAME_41 = c.String(maxLength: 250),
                        AVALUE_41 = c.String(maxLength: 250),
                        ACODE_42 = c.String(maxLength: 50),
                        ANAME_42 = c.String(maxLength: 250),
                        AVALUE_42 = c.String(maxLength: 250),
                        ACODE_43 = c.String(maxLength: 50),
                        ANAME_43 = c.String(maxLength: 250),
                        AVALUE_43 = c.String(maxLength: 250),
                        ACODE_44 = c.String(maxLength: 50),
                        ANAME_44 = c.String(maxLength: 250),
                        AVALUE_44 = c.String(maxLength: 250),
                        ACODE_45 = c.String(maxLength: 50),
                        ANAME_45 = c.String(maxLength: 250),
                        AVALUE_45 = c.String(maxLength: 250),
                        ACODE_46 = c.String(maxLength: 50),
                        ANAME_46 = c.String(maxLength: 250),
                        AVALUE_46 = c.String(maxLength: 250),
                        ACODE_47 = c.String(maxLength: 50),
                        ANAME_47 = c.String(maxLength: 250),
                        AVALUE_47 = c.String(maxLength: 250),
                        ACODE_48 = c.String(maxLength: 50),
                        ANAME_48 = c.String(maxLength: 250),
                        AVALUE_48 = c.String(maxLength: 250),
                        ACODE_49 = c.String(maxLength: 50),
                        ANAME_49 = c.String(maxLength: 250),
                        AVALUE_49 = c.String(maxLength: 250),
                        ACODE_50 = c.String(maxLength: 50),
                        ANAME_50 = c.String(maxLength: 250),
                        AVALUE_50 = c.String(maxLength: 250),
                        PICKUP_POINT = c.String(maxLength: 30),
                    })
                .PrimaryKey(t => t.RecNum);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.TEMP_BRG_MP");
        }
    }
}
