// <auto-generated />
namespace MasterOnline.ErasoftContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_merek_tempBrgMp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_merek_tempBrgMp));
        
        string IMigrationMetadata.Id
        {
            get { return "201810310800596_add_merek_tempBrgMp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
