// <auto-generated />
namespace MasterOnline.ErasoftContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_sellersku_tempbrgmp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_sellersku_tempbrgmp));
        
        string IMigrationMetadata.Id
        {
            get { return "201812110725465_add_sellersku_tempbrgmp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
