// <auto-generated />
namespace MasterOnline.ErasoftContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlterSTF02H : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterSTF02H));
        
        string IMigrationMetadata.Id
        {
            get { return "201807050443590_AlterSTF02H"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
