// <auto-generated />
namespace MasterOnline.ErasoftContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class category_attribute_attributeOpt_lazada_stf02h_31_50 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(category_attribute_attributeOpt_lazada_stf02h_31_50));
        
        string IMigrationMetadata.Id
        {
            get { return "201808291000403_category_attribute_attributeOpt_lazada_stf02h_31_50"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
