// <auto-generated />
namespace MasterOnline.ErasoftContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlterPBT01B : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterPBT01B));
        
        string IMigrationMetadata.Id
        {
            get { return "201804020755413_AlterPBT01B"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
