// <auto-generated />
namespace MasterOnline.ErasoftContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class API_LOG_MARKETPLACE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(API_LOG_MARKETPLACE));
        
        string IMigrationMetadata.Id
        {
            get { return "201808290510311_API_LOG_MARKETPLACE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
