// <auto-generated />
namespace MasterOnline.ErasoftContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ARF01C_field_EMAIL_Not_Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ARF01C_field_EMAIL_Not_Required));
        
        string IMigrationMetadata.Id
        {
            get { return "201811070759330_ARF01C_field_EMAIL_Not_Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
