// <auto-generated />
namespace MasterOnline.ErasoftContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AL_AL2_AL3_SIT01A_jadi_max : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AL_AL2_AL3_SIT01A_jadi_max));
        
        string IMigrationMetadata.Id
        {
            get { return "201808290320063_AL_AL2_AL3_SIT01A_jadi_max"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
