// <auto-generated />
namespace MasterOnline.ErasoftContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class api_log_marketplace_view_dan_LOG_REQUEST_ID_di_queueFeedBlibli : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(api_log_marketplace_view_dan_LOG_REQUEST_ID_di_queueFeedBlibli));
        
        string IMigrationMetadata.Id
        {
            get { return "201809050429558_api_log_marketplace_view_dan_LOG_REQUEST_ID_di_queueFeedBlibli"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
