// <auto-generated />
namespace MasterOnline.ErasoftContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Tambah_Field_Request_rsult_danException_di_API_LOG_MARKETPLACE_PER_ITEM_VIEW : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tambah_Field_Request_rsult_danException_di_API_LOG_MARKETPLACE_PER_ITEM_VIEW));
        
        string IMigrationMetadata.Id
        {
            get { return "201809050940272_Tambah_Field_Request_rsult_danException_di_API_LOG_MARKETPLACE_PER_ITEM_VIEW"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
