// <auto-generated />
namespace MasterOnline.ErasoftContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class hapus_table_Category_attribute_attributeOpt_lazada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hapus_table_Category_attribute_attributeOpt_lazada));
        
        string IMigrationMetadata.Id
        {
            get { return "201808300251340_hapus_table_Category_attribute_attributeOpt_lazada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
