// <auto-generated />
namespace MasterOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Category_attribute_attributeOpt_lazada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Category_attribute_attributeOpt_lazada));
        
        string IMigrationMetadata.Id
        {
            get { return "201808300307125_Category_attribute_attributeOpt_lazada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
