// <auto-generated />
namespace MasterOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MO_add_col_cate_code_di_attribute_opt_lazada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MO_add_col_cate_code_di_attribute_opt_lazada));
        
        string IMigrationMetadata.Id
        {
            get { return "201810090934185_MO_add_col_cate_code_di_attribute_opt_lazada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
